### ISSUE TITLE
GitLab CI lint not working anymore without authentication

### ISSUE THREAD

**Issue by ccremer** [appuio/component-openshift4-terraform#7]
GitLab CI linting PR check fails (see details below)

Possible actions:

* Remove GitLab ci linting step
* Keep the GitLab CI linting step, but use authentication
  * Use git.vshn.net with a token
  * Use gitlab.com with a token
  * However, this check cannot be done in PR checks, since GitHub won't expose Secrets in PRs for security reasons (leaking etc.)

## Steps to Reproduce the Problem

1. `make test-cloudscale`

## Actual Behavior
See logs in https://github.com/appuio/component-openshift4-terraform/runs/2802667905?check_suite_focus=true, e.g.
```console

cat compiled/openshift4-terraform/openshift4-terraform/gitlab-ci.yml | docker run --rm -u "$(id -u)" -w /openshift4-terraform -v "${PWD}/compiled/openshift4-terraform/openshift4-terraform:/openshift4-terraform" -i docker.io/gableroux/gitlab-ci-lint:latest
...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1957  100    30  100  1927    241  15540 --:--:-- --:--:-- --:--:-- 15782
configuration is invalid, unknown status 'null'
make: *** [Makefile:58: .test] Error 254
```

Reverse-engineering https://www.github.com/GabLeRoux/docker-gitlab-ci-lint showed that the Linting is done with the live API on gitlab.com. The request fails silently with HTTP status 400 from now on.

Turns out GitLab has put the CI-lint API behind authentication: https://about.gitlab.com/releases/2021/06/01/security-release-gitlab-13-12-2-released/#unauthenticated-ci-lint-api-may-lead-to-information-disclosure-and-ssrf

## Action points

1. Introduce a simple yaml lint for testing locally
1. Create a restricted token on git.vshn.net
2. Create GH secret so that the check works when linting with git.vshn.net API (set GITLAB_API_URL with user:token@https://... in workflow)
3. Separate the live CI linting from local make targets

**Comment by ccremer** [comment]
@simu WDYT?

**Comment by simu** [comment]
> [...] GitHub won't expose Secrets in PRs for security reasons (leaking etc.)

IIRC this only applies for PRs originating from a fork of the repo, not for PRs originating from a branch within the repo.

Assuming that I'm remembering correctly, I'd suggest we go ahead and use git.vshn.net with a token for the check and accept that the check won't work correctly if there's a PR originating from a fork of the repo.

**Comment by ccremer** [comment]
Right, I mixed it up.
> Secrets are not passed to workflows that are triggered by a pull request from a fork.

However, one would still need to configure a token when executing `make test-*` locally. I suggest we can separate the linting command into its own make target so that at least Terraform test compilation can be verified locally if one is too lazy to set up a token for local tests :)

**Comment by ccremer** [comment]
Sadly it's not possible to provide the token credentials without changing the docker image used for linting. I've documented my findings here: https://github.com/GabLeRoux/docker-gitlab-ci-lint/issues/15

Until then I'd propose to simply replace this linting with a plain YAML linting for the time being.
